// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "@/components/layout/Navbar"; // Agar har page pe auto chahiye to uncomment karo
// import Footer from "@/components/layout/Footer"; // Agar har page pe auto chahiye to uncomment karo

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wayfinder | Smart Indoor Navigation",
  description: "Enterprise indoor navigation system for hospitals, malls, and offices.",
  icons: {
    icon: "/favicon.ico", // Apna logo lagana mat bhulna public folder me
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* <Navbar />  <-- Agar yahan lagaya to baaki pages se Navbar hata dena duplicate na ho */}
        {children}
        {/* <Footer />  <-- Same logic for Footer */}
      </body>
    </html>
  );
}

// import type { Metadata } from 'next';

// export const metadata: Metadata = {
//   title: {
//     default: 'Wayfinder | Premier Indoor Navigation System',
//     template: '%s | Wayfinder'
//   },
//   description: 'Enterprise-grade indoor navigation and wayfinding system for hospitals, malls, and airports. Enhance visitor experience with digital maps.',
//   keywords: ['Indoor Navigation', 'Wayfinding Kiosk', 'Digital Map', 'Hospital Navigation', 'Mall Wayfinder'],
//   openGraph: {
//     type: 'website',
//     locale: 'en_US',
//     url: 'https://wayfinder.com',
//     siteName: 'Wayfinder',
//   },
//   robots: {
//     index: true,
//     follow: true,
//   }
// }; 